In [8]:
import MDAnalysis as mda

In [ ]:
u=mda.Universe("DNA_lipids.gro")

In [10]:
chain1_N1_N3 = u.select_atoms("((resname DA DG and name N1) or (resname DT DC and name N3) or (resname HFA HFG HSA HSG and name N1) or  (resname HFT HFC HST HSC  and name N3)) and (resid 1:147)")
chain2_N1_N3 = u.select_atoms("((resname DA DG and name N1) or (resname DT DC and name N3)) and (resid 148:294)")
print(f"{len(chain1_N1_N3)}, {len(chain2_N1_N3)}")

147, 147

In [11]:
import pandas as pd

# Convert chain2_N1_N3 to a DataFrame
chain2_N1_N3_df = pd.DataFrame({
    'Atom ID': chain2_N1_N3.ids,
    'Atom Name': chain2_N1_N3.names,
    'Residue Name': chain2_N1_N3.resnames,
    'Residue ID': chain2_N1_N3.resids,
    'Segment ID': chain2_N1_N3.segids,
    'Position': list(chain2_N1_N3.positions)
})

print(chain2_N1_N3_df)

     Atom ID Atom Name Residue Name  Residue ID Segment ID  \
0       5315        N3           DC         148     SYSTEM
1       5345        N1           DG         149     SYSTEM
2       5378        N3           DC         150     SYSTEM
3       5406        N3           DT         151     SYSTEM
4       5438        N3           DT         152     SYSTEM
..       ...       ...          ...         ...        ...
142     9839        N3           DT         290     SYSTEM
143     9871        N3           DT         291     SYSTEM
144     9903        N3           DT         292     SYSTEM
145     9937        N3           DC         293     SYSTEM
146     9967        N3           DC         294     SYSTEM

                         Position
0     [177.70001, 128.53, 104.32]
1    [176.59, 131.89, 102.399994]
2    [176.55, 135.59, 102.659996]
3      [174.79001, 138.59, 101.0]
4     [172.42001, 141.14, 100.33]
..                            ...
142      [179.48, 112.08, 100.19]
143      [178.13, 115.19, 101.28]
144   [177.43, 118.21999, 102.67]
145         [177.2, 121.4, 103.6]
146      [177.44, 124.89, 104.39]

[147 rows x 6 columns]

In [12]:

# Convert chain2_N1_N3 to a DataFrame
chain1_N1_N3_df = pd.DataFrame({
    'Atom ID': chain1_N1_N3.ids,
    'Atom Name': chain1_N1_N3.names,
    'Residue Name': chain1_N1_N3.resnames,
    'Residue ID': chain1_N1_N3.resids,
    'Segment ID': chain1_N1_N3.segids,
    'Position': list(chain1_N1_N3.positions)
})

print(chain1_N1_N3_df)

     Atom ID Atom Name Residue Name  Residue ID Segment ID  \
0         18        N1           DG           1     SYSTEM
1         51        N1           DG           2     SYSTEM
2         82        N1           DA           3     SYSTEM
3        114        N1           DA           4     SYSTEM
4        146        N1           DA           5     SYSTEM
..       ...       ...          ...         ...        ...
142     5108        N1           DA         143     SYSTEM
143     5129        N1          HFA         144     SYSTEM
144     5196        N1           DG         145     SYSTEM
145     5219        N3          HSC         146     SYSTEM
146     5281        N1           DG         147     SYSTEM

                           Position
0      [178.64, 125.240005, 101.72]
1       [179.64001, 122.14, 102.14]
2       [180.27, 119.0, 102.880005]
3          [180.34, 115.64, 103.14]
4          [180.26, 112.22, 103.06]
..                              ...
142   [170.8, 140.45999, 102.53999]
143     [172.45001, 137.36, 101.94]
144  [174.08002, 134.36, 101.78001]
145         [174.33, 130.97, 100.7]
146    [177.34, 128.38, 101.350006]

[147 rows x 6 columns]

In [13]:
# Reverse chain2_N1_N3_df based on its index
chain2_N1_N3_df_reversed = chain2_N1_N3_df.iloc[::-1].reset_index(drop=True)

print(chain2_N1_N3_df_reversed)

     Atom ID Atom Name Residue Name  Residue ID Segment ID  \
0       9967        N3           DC         294     SYSTEM
1       9937        N3           DC         293     SYSTEM
2       9903        N3           DT         292     SYSTEM
3       9871        N3           DT         291     SYSTEM
4       9839        N3           DT         290     SYSTEM
..       ...       ...          ...         ...        ...
142     5438        N3           DT         152     SYSTEM
143     5406        N3           DT         151     SYSTEM
144     5378        N3           DC         150     SYSTEM
145     5345        N1           DG         149     SYSTEM
146     5315        N3           DC         148     SYSTEM

                         Position
0        [177.44, 124.89, 104.39]
1           [177.2, 121.4, 103.6]
2     [177.43, 118.21999, 102.67]
3        [178.13, 115.19, 101.28]
4        [179.48, 112.08, 100.19]
..                            ...
142   [172.42001, 141.14, 100.33]
143    [174.79001, 138.59, 101.0]
144  [176.55, 135.59, 102.659996]
145  [176.59, 131.89, 102.399994]
146   [177.70001, 128.53, 104.32]

[147 rows x 6 columns]

In [14]:
merged_df = pd.DataFrame({
    'Atom ID (chain1)': chain1_N1_N3_df['Atom ID'],
    'Atom ID (chain2)': chain2_N1_N3_df_reversed['Atom ID'],
    'Residue Name (chain1)': chain1_N1_N3_df['Residue Name'],
    
    'Residue Name (chain2)': chain2_N1_N3_df_reversed['Residue Name'],
    'Residue ID (chain1)': chain1_N1_N3_df['Residue ID'],
    'Residue ID (chain2)': chain2_N1_N3_df_reversed['Residue ID']
   
})
#print(merged_df)
merged_df.to_csv('merged_df.csv', index=False)
merged_df

,Atom ID (chain1),Atom ID (chain2),Residue Name (chain1),Residue Name (chain2),Residue ID (chain1),Residue ID (chain2)
0,18,9967,DG,DC,1,294
1,51,9937,DG,DC,2,293
2,82,9903,DA,DT,3,292
3,114,9871,DA,DT,4,291
4,146,9839,DA,DT,5,290
...,...,...,...,...,...,...
142,5108,5438,DA,DT,143,152
143,5129,5406,HFA,DT,144,151
144,5196,5378,DG,DC,145,150
145,5219,5345,HSC,DG,146,149
146,5281,5315,DG,DC,147,148

In [15]:
# Add new columns with default values
merged_df['atom_i'] = merged_df['Atom ID (chain1)']
merged_df['atom_j'] = merged_df['Atom ID (chain2)']
merged_df['func'] = 10  
merged_df['r0'] = 0.270  
merged_df['r1'] = 0.299  #
merged_df['r2'] = 0.330 # 
merged_df['k(kJ mol^-1 nm^-2)'] = 1000  # Example default value
merged_df[";"] = ";"  # Adding a column with a semicolon as its value
merged_df['Atom ID (chain1)'] = chain1_N1_N3_df['Atom ID']
merged_df['Atom ID (chain2)'] = chain2_N1_N3_df_reversed['Atom ID']
merged_df['Residue Name (chain1)'] = chain1_N1_N3_df['Residue Name']
merged_df['Residue Name (chain2)'] = chain2_N1_N3_df_reversed['Residue Name']
merged_df['Residue ID (chain1)'] = chain1_N1_N3_df['Residue ID']
merged_df['Residue ID (chain2)'] = chain2_N1_N3_df_reversed['Residue ID']
# Create a new DataFrame with selected columns from merged_df
new_df = merged_df[['atom_i', 'atom_j', 'func', 'r0', 'r1', 'r2', 'k(kJ mol^-1 nm^-2)',";",'Atom ID (chain1)','Atom ID (chain2)','Residue Name (chain1)','Residue Name (chain2)','Residue ID (chain1)','Residue ID (chain2)' ]]

new_df

,atom_i,atom_j,func,r0,r1,r2,k(kJ mol^-1 nm^-2),;,Atom ID (chain1),Atom ID (chain2),Residue Name (chain1),Residue Name (chain2),Residue ID (chain1),Residue ID (chain2)
0,18,9967,10,0.27,0.299,0.33,1000,;,18,9967,DG,DC,1,294
1,51,9937,10,0.27,0.299,0.33,1000,;,51,9937,DG,DC,2,293
2,82,9903,10,0.27,0.299,0.33,1000,;,82,9903,DA,DT,3,292
3,114,9871,10,0.27,0.299,0.33,1000,;,114,9871,DA,DT,4,291
4,146,9839,10,0.27,0.299,0.33,1000,;,146,9839,DA,DT,5,290
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
142,5108,5438,10,0.27,0.299,0.33,1000,;,5108,5438,DA,DT,143,152
143,5129,5406,10,0.27,0.299,0.33,1000,;,5129,5406,HFA,DT,144,151
144,5196,5378,10,0.27,0.299,0.33,1000,;,5196,5378,DG,DC,145,150
145,5219,5345,10,0.27,0.299,0.33,1000,;,5219,5345,HSC,DG,146,149
146,5281,5315,10,0.27,0.299,0.33,1000,;,5281,5315,DG,DC,147,148

In [16]:
# Open the topology file in append mode
with open('create_topology_file.itp', 'a') as topo_file:
    # Write the [ bonds ] section header
    topo_file.write('\n[ bonds ]\n')
    
    # Iterate through new_df and write each row in the desired format
    for _, row in new_df.iterrows():
        topo_file.write(f"{row['atom_i']:>5} {row['atom_j']:>5} {row['func']:>5} {row['r0']:>5} {row['r1']:>8.3f} {row['r2']:>8.3f} {row['k(kJ mol^-1 nm^-2)']:>8} {row[';']} {row['Residue Name (chain1)']} {row['Residue Name (chain2)']} {row['Residue ID (chain1)']} {row['Residue ID (chain2)']}\n")

# Fix DNA

In [18]:
import MDAnalysis as mda
import pandas as pd
u=mda.Universe("DMPC_DMTAP_single_O1P_O2P_clean_DNA_new1_box_min.gro")
P_atoms = u.select_atoms("resname DA DG DT DC HFA HFG HSA HSG HST HFT HSC HFC and name P")
print(f"{len(P_atoms)}")
# Convert P_atoms to a DataFrame
P_atoms_df = pd.DataFrame({
    'Atom ID': P_atoms.ids,
    'Atom Name': P_atoms.names,
    'Residue Name': P_atoms.resnames,
    'Residue ID': P_atoms.resids})
# print(P_atoms_df.tail(2))


DNA_fix = P_atoms_df[P_atoms_df['Residue ID'].isin([3, 292, 40, 255,71, 224, 113, 182 ])]
print(DNA_fix) 


n = len(DNA_fix)

rest = pd.DataFrame({
    'i': DNA_fix['Atom ID'],
    'func': [2] * n,
    'g': [5] * n,
    'r': [3] * n,
    'f': [1000] * n,
})

# --------------------------------------------------
# 6. Add per-line comments (for humans)
# --------------------------------------------------
rest['comment'] = (
    DNA_fix['Residue Name'] +
    ' resid ' +
    DNA_fix['Residue ID'].astype(str) +
    ' ' +
    DNA_fix['Atom Name']
)

# --------------------------------------------------
# 7. Write GROMACS POSRES file
# --------------------------------------------------
with open("posre_fixDNA.itp", "w") as f:
    f.write("#ifdef POSRESFIXDNA\n")
    f.write("; i  funct  g  r(nm)  k(kJ mol^-1 nm^-2)\n")
    f.write("[ position_restraints ]\n")

    for _, row in rest.iterrows():
        f.write(
            f"{int(row['i']):>6} "
            f"{int(row['func']):>2} "
            f"{int(row['g']):>2} "
            f"{int(row['r']):>3} "
            f"{int(row['f']):>6} "
            f"; {row['comment']}\n"
        )

    f.write("#endif\n")

print("posre_fixDNA.itp written successfully")

288
     Atom ID Atom Name Residue Name  Residue ID
1         65         P           DA           3
37      1398         P           DA          40
67      2515         P           DA          71
107     4024         P           DA         113
175     6376         P           DT         182
217     7717         P           DT         224
248     8706         P           DT         255
285     9886         P           DT         292
posre_fixDNA.itp written successfully